In [66]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [67]:
# dataset from the dataset folder
train = pd.read_excel("datasets/Flight_Prediction/Data_Train.xlsx")
test = pd.read_excel("datasets/Flight_Prediction/Test_set.xlsx")
display(train, test)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info
...,...,...,...,...,...,...,...,...,...,...
2666,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info
2667,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info
2668,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info
2669,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info
2670,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info

In [68]:
# let's combine the test and train datasets to perfrom EDA and FE on both the datasets
df = pd.concat([train, test], ignore_index=True)
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0
...,...,...,...,...,...,...,...,...,...,...,...
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [69]:
# print(train.shape[0]+test.shape[0],train.shape[1])
# print(df.shape)
# merged correctly!

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Date_of_Journey  13354 non-null  str
 2   Source           13354 non-null  str
 3   Destination      13354 non-null  str
 4   Route            13353 non-null  str
 5   Dep_Time         13354 non-null  str
 6   Arrival_Time     13354 non-null  str
 7   Duration         13354 non-null  str
 8   Total_Stops      13353 non-null  str
 9   Additional_Info  13354 non-null  str
 10  Price            10683 non-null  float64
dtypes: float64(1), str(10)
memory usage: 1.1 MB

# Starting with FE process:

### Observations
1. date_of_journey are in str/object format. We need to convert them to datetime format for better analysis.
2. also we need to convert categorical features to numerical features for better analysis and model building.

In [70]:
# Convert to dateTime:
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'], dayfirst=True)

In [71]:
# we need: 
df['Day'] = df['Date_of_Journey'].dt.day
df['Month'] = df['Date_of_Journey'].dt.month
df['Year'] = df['Date_of_Journey'].dt.year

In [72]:
df
# we could also have using df.str.split('/').str[0(for day) or 1 or 2]

df.drop(['Date_of_Journey'], axis = 1, inplace=True)

In [73]:
# just testing is what i remember is correct or not:
df_dummy = df.copy(deep=True)
# df_dummy['Date_of_Journey'] = pd.to_datetime(df_dummy['Date_of_Journey'], dayfirst=True)
# df_dummy['Date_of_Journey'].dt.month
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,Air India,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN,6,6,2019
13350,IndiGo,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN,27,3,2019
13351,Jet Airways,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN,6,3,2019
13352,Air India,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN,6,3,2019
13353,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN,15,6,2019

In [74]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Dep_Time         13354 non-null  str
 5   Arrival_Time     13354 non-null  str
 6   Duration         13354 non-null  str
 7   Total_Stops      13353 non-null  str
 8   Additional_Info  13354 non-null  str
 9   Price            10683 non-null  float64
 10  Day              13354 non-null  int32
 11  Month            13354 non-null  int32
 12  Year             13354 non-null  int32
dtypes: float64(1), int32(3), str(9)
memory usage: 1.2 MB

In [75]:
df.describe().columns

Index(['Price', 'Day', 'Month', 'Year'], dtype='str')

In [76]:
df.columns.tolist()

['Airline',
 'Source',
 'Destination',
 'Route',
 'Dep_Time',
 'Arrival_Time',
 'Duration',
 'Total_Stops',
 'Additional_Info',
 'Price',
 'Day',
 'Month',
 'Year']

In [ ]:
def notints(df):
    ints = df.describe().columns.tolist()
    alls = df.columns.tolist()
    return [i for i in alls if i not in ints]
notints(df) # these are the ones we need to change to numerical

['Airline',
 'Source',
 'Destination',
 'Route',
 'Dep_Time',
 'Arrival_Time',
 'Duration',
 'Total_Stops',
 'Additional_Info']

In [78]:
# for Arrival_Time we can't use to_datetime thus we'll using str thingy
df_dummy['Arrival_Time'].str.split(" ").str[0]
#since we need jsut the time let's simpley extract the 0th index ones 

# or even better let's try lambda functions
df_dummy['Arrival_Time'].apply(func= lambda x: x.split(' ')[0])

0        01:10
1        13:15
2        04:25
3        23:30
4        21:35
         ...
13349    20:25
13350    16:55
13351    04:25
13352    19:15
13353    19:15
Name: Arrival_Time, Length: 13354, dtype: str

In [79]:
df['Arrival_Time']= df['Arrival_Time'].apply(func= lambda x: x.split(' ')[0])
# Done with this let's check if there's any null values or not

In [80]:
# df.isna().sum()
# before that let's take out the hour and min from arrival time
df['Arrival_Hour']= df['Arrival_Time'].str.split(':').str[0].astype(int)
df['Arrival_Min']= df['Arrival_Time'].str.split(':').str[1].astype(int)
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,Air India,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25,23h 55m,1 stop,No info,NaN,6,6,2019,20,25
13350,IndiGo,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN,27,3,2019,16,55
13351,Jet Airways,Delhi,Cochin,DEL → BOM → COK,21:50,04:25,6h 35m,1 stop,No info,NaN,6,3,2019,4,25
13352,Air India,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN,6,3,2019,19,15
13353,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN,15,6,2019,19,15

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Dep_Time         13354 non-null  str
 5   Arrival_Time     13354 non-null  str
 6   Duration         13354 non-null  str
 7   Total_Stops      13353 non-null  str
 8   Additional_Info  13354 non-null  str
 9   Price            10683 non-null  float64
 10  Day              13354 non-null  int32
 11  Month            13354 non-null  int32
 12  Year             13354 non-null  int32
 13  Arrival_Hour     13354 non-null  int64
 14  Arrival_Min      13354 non-null  int64
dtypes: float64(1), int32(3), int64(2), str(9)
memory usage: 1.4 MB

In [82]:
# ley's quickly do the same for Departure time

df['Dep_Hour']= df['Dep_Time'].str.split(':').str[0].astype(int)
df['Dep_Min']= df['Dep_Time'].str.split(':').str[1].astype(int)
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,Air India,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25,23h 55m,1 stop,No info,NaN,6,6,2019,20,25,20,30
13350,IndiGo,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN,27,3,2019,16,55,14,20
13351,Jet Airways,Delhi,Cochin,DEL → BOM → COK,21:50,04:25,6h 35m,1 stop,No info,NaN,6,3,2019,4,25,21,50
13352,Air India,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN,6,3,2019,19,15,4,0
13353,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN,15,6,2019,19,15,4,55

In [83]:
# now we don't need the Arrival or Dep time 
df.drop(['Arrival_Time'], axis = 1, inplace = True)
df.drop(['Dep_Time'], axis = 1, inplace = True)

### handling categorical features: Total_Stops

In [65]:
df[df['Total_Stops'].isnull()]
# Since we can see that only one null value is there in... entire dataset for total spots stops Thus we can directly either manage can only change the data or can define null as 1. since we can see in the detail. that the source and destination is single journey trip 

# let's simply change the data to specific row to avoid confusion

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480.0,6,5,2019,9,25,9,45

In [85]:
# let's focus on Routes now 
df['Total_Stops'].unique() # as we can see; lets map it

stops = {
    'non-stop': 0,
    '1 stop': 1,
    '2 stops': 2,
    '3 stops': 3,
    '4 stops': 4,
    'nan': 1 # setting it default
}

In [86]:
df['Total_Stops'] = df['Total_Stops'].map(stops)

In [89]:
df.head()
df.drop(['Route'], axis = 1, inplace=True)

## just casually go though feature to find meaningful thing to deduce or perfrom FE upon

In [93]:
df['Additional_Info'].unique() 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Duration         13354 non-null  str
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  str
 6   Price            10683 non-null  float64
 7   Day              13354 non-null  int32
 8   Month            13354 non-null  int32
 9   Year             13354 non-null  int32
 10  Arrival_Hour     13354 non-null  int64
 11  Arrival_Min      13354 non-null  int64
 12  Dep_Hour         13354 non-null  int64
 13  Dep_Min          13354 non-null  int64
dtypes: float64(2), int32(3), int64(4), str(5)
memory usage: 1.3 MB

In [97]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50

In [ ]:
# df['Duration_in_Min']= (df['Duration'].str.split(' ').str[0].str[:-1].astype(int)*60)+ (df['Duration'].str.split(' ').str[1].str[:-1].astype(int))
df['Duration_hr']= df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['Duration_hr']= df['Duration'].str.split(' ').str[0].str.split('h').str[0]
# df['Duration'].apply(func = lambda x: x.split(' ')[0][:-1]).isna()

0         2
1         7
2        19
3         5
4         4
         ..
13349    23
13350     2
13351     6
13352    15
13353    14
Name: Duration, Length: 13354, dtype: object

In [158]:
df[df['Duration']=='5m'] #only 2 dataset that too seems like an issue 5m trip how? 
# let's simply drop it in that case

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Day, Month, Year, Arrival_Hour, Arrival_Min, Dep_Hour, Dep_Min]
Index: []

In [157]:
df.drop(6474, axis = 0, inplace=True)
df.drop(13343, axis = 0, inplace=True)

In [ ]:
# now we won't get the error:
df['Duration_Hr']= (df['Duration'].str.split(' ').str[0].str[:-1].astype(int)*60)

In [ ]:
def hr_min(duration):
    # duration = [["7h 25m"], ["19h"]]
    time = duration.split()
    if len(time)==1:
        return 0
    else:
        return int(time[-1][:-1])
    # for i in duration.str.split(' ').str[1]:
    #     if i!= np.nan:
    #         return int(i)
    #     else:
    #         return 0

df['Duration_Min'] = df['Duration'].apply(func=hr_min)
# display(hr_min("7h"))

In [213]:
df['Duration_in_Min'] =df['Duration_Hr'] + df['Duration_Min']

In [214]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Duration_in_Min,Duration_Hr,Duration_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,170,120,50
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,445,420,25
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,1140,1140,0
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,325,300,25
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,285,240,45

In [ ]:
df.drop(['Duration'], axis = 1, inplace=True)
df.info() #let's check for anythign else..

<class 'pandas.DataFrame'>
Index: 13352 entries, 0 to 13353
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13352 non-null  str
 1   Source           13352 non-null  str
 2   Destination      13352 non-null  str
 3   Total_Stops      13351 non-null  float64
 4   Additional_Info  13352 non-null  str
 5   Price            10682 non-null  float64
 6   Day              13352 non-null  int32
 7   Month            13352 non-null  int32
 8   Year             13352 non-null  int32
 9   Arrival_Hour     13352 non-null  int64
 10  Arrival_Min      13352 non-null  int64
 11  Dep_Hour         13352 non-null  int64
 12  Dep_Min          13352 non-null  int64
 13  Duration_in_Min  13352 non-null  int64
 14  Duration_Hr      13352 non-null  int64
 15  Duration_Min     13352 non-null  int64
dtypes: float64(2), int32(3), int64(7), str(4)
memory usage: 1.6 MB

### Handling Airline feature: Categorical -> Numerical

In [ ]:
df['Airline'].unique().tolist()

['IndiGo',
 'Air India',
 'Jet Airways',
 'SpiceJet',
 'Multiple carriers',
 'GoAir',
 'Vistara',
 'Air Asia',
 'Vistara Premium economy',
 'Jet Airways Business',
 'Multiple carriers Premium economy',
 'Trujet']

In [ ]:
airlines = {
    'IndiGo': ,
    'Air India',
    'Jet Airways',
    'SpiceJet',
    'Multiple carriers',
    'GoAir',
    'Vistara',
    'Air Asia',
    'Vistara Premium economy',
    'Jet Airways Business',
    'Multiple carriers Premium economy',
    'Trujet'
}

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()

### **Doing the label encoding for all the categorical data**

In [229]:
df['Airline'] = labelEncoder.fit_transform(df['Airline'])
df['Source'] = labelEncoder.fit_transform(df['Source'])
df['Destination'] = labelEncoder.fit_transform(df['Destination'])
df['Additional_Info'] = labelEncoder.fit_transform(df['Additional_Info'])

In [231]:
# df['Additional_Info'].unique()
df.head()
df.info()

<class 'pandas.DataFrame'>
Index: 13352 entries, 0 to 13353
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13352 non-null  int64
 1   Source           13352 non-null  int64
 2   Destination      13352 non-null  int64
 3   Total_Stops      13351 non-null  float64
 4   Additional_Info  13352 non-null  int64
 5   Price            10682 non-null  float64
 6   Day              13352 non-null  int32
 7   Month            13352 non-null  int32
 8   Year             13352 non-null  int32
 9   Arrival_Hour     13352 non-null  int64
 10  Arrival_Min      13352 non-null  int64
 11  Dep_Hour         13352 non-null  int64
 12  Dep_Min          13352 non-null  int64
 13  Duration_in_Min  13352 non-null  int64
 14  Duration_Hr      13352 non-null  int64
 15  Duration_Min     13352 non-null  int64
dtypes: float64(2), int32(3), int64(11)
memory usage: 1.6 MB

### **We can also do One Hot encoding for all the categorical data**

In [232]:
from sklearn.preprocessing import OneHotEncoder
One_hot = OneHotEncoder()

In [234]:
# df_dummy['Airline'] = One_hot.fit_transform(df_dummy['Airline'])
# df_dummy['Source'] = One_hot.fit_transform(df_dummy['Source'])
# df_dummy['Destination'] = One_hot.fit_transform(df_dummy['Destination'])
# df_dummy['Additional_Info'] = One_hot.fit_transform(df_dummy['Additional_Info'])

# this isn't working cause we're getting series type and it requires dataframe

In [240]:
# thus back to get_dummies
pd.get_dummies(data = df, columns= ['Airline','Source','Destination','Additional_Info'], drop_first=1).astype('Int64')

,Total_Stops,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Duration_in_Min,...,Destination_5,Additional_Info_1,Additional_Info_2,Additional_Info_3,Additional_Info_4,Additional_Info_5,Additional_Info_6,Additional_Info_7,Additional_Info_8,Additional_Info_9
0,0,3897,24,3,2019,1,10,22,20,170,...,1,0,0,0,0,0,0,0,1,0
1,2,7662,1,5,2019,13,15,5,50,445,...,0,0,0,0,0,0,0,0,1,0
2,2,13882,9,6,2019,4,25,9,25,1140,...,0,0,0,0,0,0,0,0,1,0
3,1,6218,12,5,2019,23,30,18,5,325,...,0,0,0,0,0,0,0,0,1,0
4,1,13302,1,3,2019,21,35,16,50,285,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,1,<NA>,6,6,2019,20,25,20,30,1435,...,0,0,0,0,0,0,0,0,1,0
13350,0,<NA>,27,3,2019,16,55,14,20,155,...,0,0,0,0,0,0,0,0,1,0
13351,1,<NA>,6,3,2019,4,25,21,50,395,...,0,0,0,0,0,0,0,0,1,0
13352,1,<NA>,6,3,2019,19,15,4,0,915,...,0,0,0,0,0,0,0,0,1,0
13353,1,<NA>,15,6,2019,19,15,4,55,860,...,0,0,0,0,0,0,0,0,1,0

In [241]:
df

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Duration_in_Min,Duration_Hr,Duration_Min
0,3,0,5,0.0,8,3897.0,24,3,2019,1,10,22,20,170,120,50
1,1,3,0,2.0,8,7662.0,1,5,2019,13,15,5,50,445,420,25
2,4,2,1,2.0,8,13882.0,9,6,2019,4,25,9,25,1140,1140,0
3,3,3,0,1.0,8,6218.0,12,5,2019,23,30,18,5,325,300,25
4,3,0,5,1.0,8,13302.0,1,3,2019,21,35,16,50,285,240,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,1,3,0,1.0,8,NaN,6,6,2019,20,25,20,30,1435,1380,55
13350,3,3,0,0.0,8,NaN,27,3,2019,16,55,14,20,155,120,35
13351,4,2,1,1.0,8,NaN,6,3,2019,4,25,21,50,395,360,35
13352,1,2,1,1.0,8,NaN,6,3,2019,19,15,4,0,915,900,15
13353,6,2,1,1.0,8,NaN,15,6,2019,19,15,4,55,860,840,20