# 100 pandas puzzles

Inspired by [100 Numpy exerises](https://github.com/rougier/numpy-100), here are 100* short puzzles for testing your knowledge of [pandas'](http://pandas.pydata.org/) power.

Since pandas is a large library with many different specialist features and functions, these excercises focus mainly on the fundamentals of manipulating data (indexing, grouping, aggregating, cleaning), making use of the core DataFrame and Series objects. 

Many of the excerises here are stright-forward in that the solutions require no more than a few lines of code (in pandas or NumPy... don't go using pure Python or Cython!). Choosing the right methods and following best practices is the underlying goal.

The exercises are loosely divided in sections. Each section has a difficulty rating; these ratings are subjective, of course, but should be a seen as a rough guide as to how inventive the required solution is.

If you're just starting out with pandas and you are looking for some other resources, the official documentation  is very extensive. In particular, some good places get a broader overview of pandas are...

- [10 minutes to pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)
- [pandas basics](http://pandas.pydata.org/pandas-docs/stable/basics.html)
- [tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html)
- [cookbook and idioms](http://pandas.pydata.org/pandas-docs/stable/cookbook.html#cookbook)

Enjoy the puzzles!

\* *the list of exercises is not yet complete! Pull requests or suggestions for additional exercises, corrections and improvements are welcomed.*

## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy* 

**1.** Import pandas under the alias `pd`.

In [141]:
import pandas as pd

**2.** Print the version of pandas that has been imported.

In [142]:
pd.__version__

'3.0.0'

**3.** Print out all the *version* information of the libraries that are required by the pandas library.

In [143]:
?pd.__version__

Type:        str
String form: 3.0.0
Length:      5
Docstring:
str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [144]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [145]:
df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     str
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 400.0+ bytes

**6.** Return the first 3 rows of the DataFrame `df`.

In [146]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [147]:
df[["animal", "age"]]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [148]:
# display(df.loc([3,4,8], ['animal', 'age']))
# display(df.iloc[1:, 1:])
# display(df.columns.get_loc('animal'))
display(df.iloc[[3,4,8], 0:2])

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Select only the rows where the number of visits is greater than 3.

In [149]:
df[df["visits"]>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**10.** Select the rows where the age is missing, i.e. it is `NaN`.

In [150]:
df[df["age"].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [151]:
df[~pd.notna(df["age"])] #this is how to find the the null or not null values

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [152]:
df[(df["animal"]=="cat") & (df["age"]<3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** Select the rows the age is between 2 and 4 (inclusive).

In [153]:
df[(df["age"]>=2) & (df["age"]<=4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** Change the age in row 'f' to 1.5.

In [154]:
# how to get the fth row of the dataframe
df.loc["f","age"] = 1.5
df.loc["f"]

animal      cat
age         1.5
visits        3
priority     no
Name: f, dtype: object

**14.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [155]:
df["visits"].value_counts().sum()

np.int64(10)

**15.** Calculate the mean age for each different animal in `df`.

In [156]:
# df_animal = df.groupby("animal")
# df_animal["age"].mean()
df.groupby("animal")["age"].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [157]:
df_copy = df.copy(deep=True)

In [158]:
to_add = {
    'animal': ["fox"],
    'age': [7.5],
    'visits': [5],
    'priority': ["yes"]
}
new_df = pd.DataFrame(to_add, index = ['k'])
# df = df.add(to_add)
df_copy = pd.concat((df, new_df))
display(df_copy)

# how dropping the row added
# df.drop(index='k')
df_copy.drop(index = 'k', inplace = True)
df_copy

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    fox  7.5       5      yes

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**17.** Count the number of each type of animal in `df`.

In [159]:
df.animal.value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [160]:
df.sort_values(by=["age"], ascending=False)
df.sort_values(by=["visits"], ascending=True)

  animal  age  visits priority
a    cat  2.5       1      yes
h    cat  NaN       1      yes
g  snake  4.5       1       no
j    dog  3.0       1       no
e    dog  5.0       2       no
c  snake  0.5       2       no
i    dog  7.0       2       no
b    cat  3.0       3      yes
f    cat  1.5       3       no
d    dog  NaN       3      yes

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [161]:
df_copy.priority = df_copy.priority.apply(lambda x: "True" if x == 'yes' else "False")
df_copy

  animal  age  visits priority
a    cat  2.5       1     True
b    cat  3.0       3     True
c  snake  0.5       2    False
d    dog  NaN       3     True
e    dog  5.0       2    False
f    cat  1.5       3    False
g  snake  4.5       1    False
h    cat  NaN       1     True
i    dog  7.0       2    False
j    dog  3.0       1    False

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [162]:
df_copy.animal = df_copy.animal.replace({"snake": "python"}, inplace=True)
df_copy

/tmp/ipykernel_6061/4144104216.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_copy.animal = df_copy.animal.replace({"snake": "python"}, inplace=True)

   animal  age  visits priority
a     cat  2.5       1     True
b     cat  3.0       3     True
c  python  0.5       2    False
d     dog  NaN       3     True
e     dog  5.0       2    False
f     cat  1.5       3    False
g  python  4.5       1    False
h     cat  NaN       1     True
i     dog  7.0       2    False
j     dog  3.0       1    False

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (*hint: use a pivot table*).

In [163]:
display(df.groupby(["animal", "visits"])['age'].mean())
# how to create a pivot table? 
display(df.pivot_table(index= 'animal', columns=["visits"], values= "age", aggfunc="mean"))

animal  visits
cat     1         2.50
        3         2.25
dog     1         3.00
        2         6.00
        3          NaN
snake   1         4.50
        2         0.50
Name: age, dtype: float64

visits    1    2     3
animal
cat     2.5  NaN  2.25
dog     3.0  6.0   NaN
snake   4.5  0.5   NaN

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**22.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

You should be left with a column containing the following values:

```python
1, 2, 3, 4, 5, 6, 7
```

In [164]:
df = pd.DataFrame({"A": [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def lst(ls):
    # i = 0
    # new = []
    # while i !=len(ls):
    #     if ls[i]!=ls[i-1]:
    #         new.append(ls[i])
    #     i+=1
    # return 
    return list(set(ls))

In [165]:
# print(lst(df["A"]))
display(df['A'].drop_duplicates())

0    1
1    2
3    3
4    4
5    5
8    6
9    7
Name: A, dtype: int64

**23.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [166]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
df

          0         1         2
0  0.664463  0.964772  0.356611
1  0.698599  0.171532  0.823583
2  0.804515  0.037703  0.094000
3  0.924639  0.537562  0.038988
4  0.270407  0.146083  0.693714

In [167]:
display(df.mean(axis=1))
display(df-df.mean(axis=1))
df.dropna(axis=1)
# display(df.subtract(df.mean(axis=1)))

0    0.661949
1    0.564571
2    0.312073
3    0.500396
4    0.370068
dtype: float64

          0         1         2   3   4
0  0.002514  0.400201  0.044538 NaN NaN
1  0.036651 -0.393040  0.511510 NaN NaN
2  0.142566 -0.526868 -0.218073 NaN NaN
3  0.262690 -0.027010 -0.273085 NaN NaN
4 -0.391542 -0.418488  0.381641 NaN NaN

          0         1         2
0  0.664463  0.964772  0.356611
1  0.698599  0.171532  0.823583
2  0.804515  0.037703  0.094000
3  0.924639  0.537562  0.038988
4  0.270407  0.146083  0.693714

**24.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum?  Return that column's label.

In [168]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
display(df.sum(axis=0).idxmin()) #this is how to find the column with the minimum sum

'h'

**25.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [169]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
display(df)
df.value_counts()
df.drop_duplicates()

   0  1  2
0  0  0  0
1  0  1  0
2  0  0  0
3  1  0  1
4  0  1  0
5  0  1  0
6  0  0  0
7  0  1  0
8  1  0  1
9  0  0  0

   0  1  2
0  0  0  0
1  0  1  0
3  1  0  1

The next three puzzles are slightly harder.


**26.** In the cell below, you have a DataFrame `df` that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values. 

For each row of the DataFrame, find the *column* which contains the *third* NaN value.

You should return a Series of column labels: `e, c, d, h, d`

In [170]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)
df
# write a solution to the question here
# below's the solution!

      a   b     c     d     e     f     g     h     i     j
0  0.04 NaN   NaN  0.25   NaN  0.43  0.71  0.51   NaN   NaN
1   NaN NaN   NaN  0.04  0.76   NaN   NaN  0.67  0.76  0.16
2   NaN NaN  0.50   NaN  0.31  0.40   NaN   NaN  0.24  0.01
3  0.49 NaN   NaN  0.62  0.73  0.26  0.85   NaN   NaN   NaN
4   NaN NaN  0.41   NaN  0.05   NaN  0.61   NaN  0.48  0.68

In [171]:
# so baically you've to start with each row and return the name of colm which's 3rd to have NaN
def iter3(lst, n=3):
    cnt = 0
    for col, val in lst.items():
        if pd.isna(val):
            cnt+=1
            if cnt == n:
                return col
    

# iter3((df.iloc[0,:][1]), 3)
df.apply(iter3,axis = 1)

# Another and better approach
df.isna().apply(lambda row: row[row].index[2], axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: str

In [172]:
for i in df.iloc[0,:].items():
    print(i)

('a', 0.04)
('b', nan)
('c', nan)
('d', 0.25)
('e', nan)
('f', 0.43)
('g', 0.71)
('h', 0.51)
('i', nan)
('j', nan)

**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals': 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [173]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
# display(df.sort_values(by = 'vals',ascending=False))
# write a solution to the question here
# display(df.groupby('grps', sort=True).head(3))
# to find the sum of the 3 largest elements on the groups

# display(df.groupby("grps")["vals"].apply(lambda x: print((x.sort_values(ascending=False)[:3]))))
display(df.groupby("grps")["vals"].apply(lambda x: x.sort_values(ascending=False)[:3].sum()))

grps
a    409
b    156
c    345
Name: vals, dtype: int64

In [174]:
display(df.groupby("grps")["vals"].apply(lambda x: x.nlargest(3).sum()))

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**28.** The DataFrame `df` constructed below has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive). 

For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

The answer should be a Series as follows:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [175]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])
display(df)
# write a solution to the question here

# let's do this step by step
# creating bins:
bins  = range(0,101,10)
# result using the bin

result  = df.groupby(pd.cut(df['A'], bins))['B'].sum()
result

     A   B
0   46  29
1   75  22
2   49  63
3   33  43
4   71  75
..  ..  ..
95  60  87
96  57  40
97  86  19
98  50  56
99  97  94

[100 rows x 2 columns]

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64

### Similar Bin type Questions

In [176]:
df = pd.DataFrame({
    'score': [5, 17, 23, 38, 41, 59, 62, 77, 88, 95],
    'points': [10, 20, 15, 30, 25, 40, 35, 45, 50, 55]
})
# want: (0,25], (25,50], (50,75], (75,100]

In [177]:
#@title sum points
bins = range(0,101,25)
df.groupby(pd.cut(df["score"], bins))["points"].sum()

score
(0, 25]       45
(25, 50]      55
(50, 75]      75
(75, 100]    150
Name: points, dtype: int64

In [178]:
#@title Left-closed vs right-closed trap
df = pd.DataFrame({
    'age': [10, 20, 30, 40, 50, 60],
    'value': [1, 2, 3, 4, 5, 6]
})
# want: [0,20), [20,40), [40,60), [60,80)

df.groupby(pd.cut(df["age"], range(0,81,20),right=False))["value"].sum() #took hint - use the parameter

age
[0, 20)     1
[20, 40)    5
[40, 60)    9
[60, 80)    6
Name: value, dtype: int64

In [179]:
#@title Missing bins trap
df = pd.DataFrame({
    'A': [3, 7, 12, 18, 19],
    'B': [10, 20, 30, 40, 50]
})
# want: (0,10], (10,20], (20,30]
df.groupby(pd.cut(df["A"], range(0,31,10),right=False),observed=False)["B"].sum() #took hint - use the parameter `observed = False -> this gives the empty or not present values too and not skip it!`

A
[0, 10)      30
[10, 20)    120
[20, 30)      0
Name: B, dtype: int64

#### WHEN TO USE pd.cut and when not:
- Use pd.cut when the grouping depends on value ranges that are:
    - not equally spaced like (0,25], (25,50], (50,75], (75,100]
    - interval label matters like (0,10] 55 ;(10,20] 233(sum of values in that range)
    - not known beforehand
    - not necessarily the same for each group

- Don't use pd.cut when the grouping depends on value ranges that are:
    - Equal-width integer bins or equally spaced; integer arithmetic is superior here eg: 
    ```python
    (df['A'] - 1) // 10

    #rule of thumb: 
    (df[col] - offset) // k
    ```
    - known beforehand

    because pd.cut is:
        - slower
        - allocates categorical objects
        - more memory
        - overkill

#### Very large datasets
- pd.cut creates categorical arrays → heavier.
**prefer integer bucketing**
    Example fast pattern: 
    ```python
    df.groupby((df['A']-1)//10)['B'].sum() 

    #Remember
    df.groupby(df.index // 100)
    # or
    df.iloc[i:i+100]
    ```

When you see a grouping problem, ask in this order:

- Step 1
    👉 Is grouping based on values or row order?
    values → continue
    row order → slicing / index math
- Step 2
    👉 Are bins equal-width integers?
    yes → prefer integer division
    no → use pd.cut
- Step 3
    👉 Is dataset huge (millions of rows)?
    yes → avoid pd.cut if possible
    no → readability may win

**29.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be 

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Make this a new column 'Y'.

In [180]:
cnt = 0

In [181]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
df

# def traceback(lst):
#     fnl = []
#     cnt = 0
#     for i in lst:
#         cnt+=1
#         if i==0:
#             fnl.append(i)
#             cnt=0
#         else: fnl.append(cnt)
#     return fnl

# traceback()

def ntrace(x):
    cnt+=1
    if x!=0:
        return cnt
    else:
        return 0

In [182]:
# what's the issue in the belpow code? the 
# cnt = 0
# df["Y"]  = df['X'].apply(lambda x: cnt+1 if x!=0 else 0) #the cnt is not increamenting, how dod i correct it? to correct it, you can use a mutable object like a list to keep track of the count. Here's how you can do it: here's how to do it using a list to keep track of the count: show
cnt = 0
for i in df.values!=0:
    if i:
        cnt+=1
    else:
        cnt= 0
    print(cnt)

mask = df["X"] !=0
# print((~mask).cumsum())
print(mask.groupby((~mask).cumsum()).cumsum())
# let's use this to solve the prev question 

display((df["X"]!=0).groupby((df["X"]==0).cumsum()).cumsum())

1
2
0
1
2
3
4
0
1
2
0    1
1    2
2    0
3    1
4    2
5    3
6    4
7    0
8    1
9    2
Name: X, dtype: int64

0    1
1    2
2    0
3    1
4    2
5    3
6    4
7    0
8    1
9    2
Name: X, dtype: int64

**30.** Consider the DataFrame constructed below which contains rows and columns of numerical data. 

Create a list of the column-row index locations of the 3 largest values in this DataFrame. In this case, the answer should be:
```
[(5, 7), (6, 4), (2, 5)]
```

In [183]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
df

    0   1   2   3   4   5   6   7
0  38  38  46  46  13  24   3  54
1  18  47   4  42   8  66  50  46
2  62  36  19  19  77  17   7  63
3  28  47  46  65  63  12  16  24
4  14  51  34  56  29  59  92  79
5  58  76  96  45  38  76  58  40
6  10  34  48  40  37  23  41  26
7  55  70  91  27  79  92  20  31

In [184]:
# df.nlargest(3, columns= [0,1,2,3,4,5,6,7], ascending=False)
df.sort_values(by= list(df.columns), ascending=False).head(3)
# now i want to find the 3 max value's (row, col) location of it
data = df.unstack().sort_values(ascending=False).head(3)
data.index.tolist()

[(2, 5), (5, 7), (6, 4)]

In [185]:
# list(df.stack().nlargest(3).index)

### Using Stack and Unstack - *flatten the DataFrame*
"if you think: “Do I need to look across the whole table at once?” then yep use stack or unstack."

    stack() → wide ➜ long : “Take columns and push them into the row index.”
    unstack() → long ➜ wide : index level → becomes columns: “Take an index level and spread it into columns.”

```python
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
data = df.unstack().sort_values(ascending=False).head(3)
data.index.tolist() 
```

1. df.stack()
    turns the df into a row and gives you a multi-index of (row, col) for each value.

**31.** You are given the DataFrame below with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Create a new column 'patched_values' which contains the same values as the 'vals' any negative values in 'vals' with the group mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

In [250]:
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

In [219]:
# df["patched_vals"] 
# df["vals"] = df["vals"].apply(lambda x: x*-1 if x<0 else x)

# df.groupby('grps')["vals"].mean()
meanA, meanB = round(df.groupby('grps')['vals'].mean(), 2)
meanA, meanB

(-0.33, 6.33)

In [ ]:
# raw wrong method - because there's a size mismatch when trying to group A and B separetly.. 
df["patched_vals"] = df[df["grps"]=="A"]["vals"].apply(lambda x: meanA if x<0 else x) #size < index size -> thus rest indes will get replaced with NaN 
df["patched_vals"] = df[df["grps"]=="B"]["vals"].apply(lambda x: meanB if x<0 else x)

<bound method DataFrame.items of     vals grps  patched_vals
0    -12    A           NaN
1     -7    B          6.33
2    -14    A           NaN
3      4    A           NaN
4     -7    A           NaN
5     28    B         28.00
6     -2    A           NaN
7     -1    A           NaN
8      8    A           NaN
9     -2    B          6.33
10    28    A           NaN
11    12    A           NaN
12    16    A           NaN
13   -24    A           NaN
14   -12    A           NaN>

In [ ]:
# correct way: Assign the defaults first then make the changes using .loc
df["patched_vals"] = df["vals"].astype('float64')

In [248]:
df.loc[(df["grps"]=="A") & (df["vals"]<0), "patched_vals"] = meanA
df.loc[(df["grps"]=="B") & (df["vals"]<0), "patched_vals"] = meanB

In [ ]:
# efficent in best way: compute once → broadcast → mask replace
means = df.groupby("grps")["vals"].transform("mean")
df["patched_vals"] = df["vals"].where(df["vals"]>=0, means)
df

    vals grps  patched_vals
0    -12    A     -0.333333
1     -7    B      6.333333
2    -14    A     -0.333333
3      4    A      4.000000
4     -7    A     -0.333333
5     28    B     28.000000
6     -2    A     -0.333333
7     -1    A     -0.333333
8      8    A      8.000000
9     -2    B      6.333333
10    28    A     28.000000
11    12    A     12.000000
12    16    A     16.000000
13   -24    A     -0.333333
14   -12    A     -0.333333

**32.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

In [ ]:
df = pd.DataFrame({'group': list('aabbabbbabab'), 
                    'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})

df

   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0

In [282]:
df["value"].rolling(3, min_periods= 1).mean()

0     1.000000
1     1.500000
2     2.000000
3     2.500000
4     2.500000
5     2.500000
6     2.500000
7     2.000000
8     4.000000
9     3.666667
10    5.000000
11    5.500000
Name: value, dtype: float64

In [ ]:
df["rolling_mean"] = (
    df.groupby("group")["value"]
    .rolling(3,min_periods = 1)
    .mean()
    .reset_index(level = 0, drop = True)
)
df
# the rolling function auto does the job for us..

   group  value  rolling_mean
0      a    1.0      1.000000
1      a    2.0      1.500000
2      b    3.0      3.000000
3      b    NaN      3.000000
4      a    2.0      1.666667
5      b    3.0      3.000000
6      b    NaN      3.000000
7      b    1.0      2.000000
8      a    7.0      3.666667
9      b    3.0      2.000000
10     a    NaN      4.500000
11     b    8.0      4.000000

In [ ]:
# Ignore: 

# vals = list(df.value)
# display(vals)

# nl = []
# net = 0
# cnt = 0
# for i in vals:
#     if not pd.isna(i):
#         cnt+=1
#         net += i
#         nl.append(net/cnt)
# nl

[1.0, 2.0, 3.0, nan, 2.0, 3.0, nan, 1.0, 7.0, 3.0, nan, 8.0]

[1.0, 1.5, 2.0, 2.0, 2.2, 2.0, 2.7142857142857144, 2.75, 3.3333333333333335]

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.

**33.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

**34.** Find the sum of the values in `s` for every Wednesday.

**35.** For each calendar month in `s`, find the mean of values.

**36.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

**37.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
```
Formatted, it looks like this:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(It's some flight data I made up; it's not meant to be accurate in any way.)

**38.** Some values in the the **FlightNumber** column are missing (they are `NaN`). These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Modify `df` to fill in these missing numbers and make the column an integer column (instead of a float column).

**39.** The **From\_To** column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame called 'temp' with the correct values. Assign the correct column names 'From' and 'To' to this temporary DataFrame.

**40.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame 'temp'. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

**41.** Delete the **From_To** column from `df` and attach the temporary DataFrame 'temp' from the previous questions.

**42**. In the **Airline** column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

**43**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

The DataFrame should look much better now.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

## Using MultiIndexes

### Go beyond flat DataFrames with additional index levels

Difficulty: *medium*

Previous exercises have seen us analysing data from DataFrames equipped with a single index level. However, pandas also gives you the possibilty of indexing your data using *multiple* levels. This is very much like adding new dimensions to a Series or a DataFrame. For example, a Series is 1D, but by using a MultiIndex with 2 levels we gain of much the same functionality as a 2D DataFrame.

The set of puzzles below explores how you might use multiple index levels to enhance data analysis.

To warm up, we'll look make a Series with two index levels.

**44**. Given the lists `letters = ['A', 'B', 'C']` and `numbers = list(range(10))`, construct a MultiIndex object from the product of the two lists. Use it to index a Series of random numbers. Call this Series `s`.

**45.** Check the index of `s` is lexicographically sorted (this is a necessary proprty for indexing to work correctly with a MultiIndex).

**46**. Select the labels `1`, `3` and `6` from the second level of the MultiIndexed Series.

**47**. Slice the Series `s`; slice up to label 'B' for the first level and from label 5 onwards for the second level.

**48**. Sum the values in `s` for each label in the first level (you should have Series giving you a total for labels A, B and C).

**49**. Suppose that `sum()` (and other methods) did not accept a `level` keyword argument. How else could you perform the equivalent of `s.sum(level=1)`?

**50**. Exchange the levels of the MultiIndex so we have an index of the form (letters, numbers). Is this new Series properly lexsorted? If not, sort it.

## Minesweeper

### Generate the numbers for safe squares in a Minesweeper grid

Difficulty: *medium* to *hard*

If you've ever used an older version of Windows, there's a good chance you've played with Minesweeper:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)


If you're not familiar with the game, imagine a grid of squares: some of these squares conceal a mine. If you click on a mine, you lose instantly. If you click on a safe square, you reveal a number telling you how many mines are found in the squares that are immediately adjacent. The aim of the game is to uncover all squares in the grid that do not contain a mine.

In this section, we'll make a DataFrame that contains the necessary data for a game of Minesweeper: coordinates of the squares, whether the square contains a mine and the number of mines found on adjacent squares.

**51**. Let's suppose we're playing Minesweeper on a 5 by 4 grid, i.e.
```
X = 5
Y = 4
```
To begin, generate a DataFrame `df` with two columns, `'x'` and `'y'` containing every coordinate for this grid. That is, the DataFrame should start:
```
   x  y
0  0  0
1  0  1
2  0  2
```

**52**. For this DataFrame `df`, create a new column of zeros (safe) and ones (mine). The probability of a mine occuring at each location should be 0.4.

**53**. Now create a new column for this DataFrame called `'adjacent'`. This column should contain the number of mines found on adjacent squares in the grid. 

(E.g. for the first row, which is the entry for the coordinate `(0, 0)`, count how many mines are found on the coordinates `(0, 1)`, `(1, 0)` and `(1, 1)`.)

**54**. For rows of the DataFrame that contain a mine, set the value in the `'adjacent'` column to NaN.

**55**. Finally, convert the DataFrame to grid of the adjacent mine counts: columns are the `x` coordinate, rows are the `y` coordinate.

## Plotting

### Visualize trends and patterns in data

Difficulty: *medium*

To really get a good understanding of the data contained in your DataFrame, it is often essential to create plots: if you're lucky, trends and anomalies will jump right out at you. This functionality is baked into pandas and the puzzles below explore some of what's possible with the library.

**56.** Pandas is highly integrated with the plotting library matplotlib, and makes plotting DataFrames very user-friendly! Plotting in a notebook environment usually makes use of the following boilerplate:

```python
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
```

matplotlib is the plotting library which pandas' plotting functionality is built upon, and it is usually aliased to ```plt```.

```%matplotlib inline``` tells the notebook to show plots inline, instead of creating them in a separate window.  

```plt.style.use('ggplot')``` is a style theme that most people find agreeable, based upon the styling of R's ggplot package.

For starters, make a scatter plot of this random data, but use black X's instead of the default markers. 

```df = pd.DataFrame({"xs":[1,5,2,8,1], "ys":[4,2,1,9,6]})```

Consult the [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html) if you get stuck!

**57.** Columns in your DataFrame can also be used to modify colors and sizes.  Bill has been keeping track of his performance at work over time, as well as how good he was feeling that day, and whether he had a cup of coffee in the morning.  Make a plot which incorporates all four features of this DataFrame.

(Hint:  If you're having trouble seeing the plot, try multiplying the Series which you choose to represent size by 10 or more)

*The chart doesn't have to be pretty: this isn't a course in data viz!*

```
df = pd.DataFrame({"productivity":[5,2,3,1,4,5,6,7,8,3,4,8,9],
                   "hours_in"    :[1,9,6,5,3,9,2,9,1,7,4,2,2],
                   "happiness"   :[2,1,3,2,3,1,2,3,1,2,2,1,3],
                   "caffienated" :[0,0,1,1,0,0,0,0,1,1,0,1,0]})
```

**58.**  What if we want to plot multiple things?  Pandas allows you to pass in a matplotlib *Axis* object for plots, and plots will also return an Axis object.

Make a bar plot of monthly revenue with a line plot of monthly advertising spending (numbers in millions)

```
df = pd.DataFrame({"revenue":[57,68,63,71,72,90,80,62,59,51,47,52],
                   "advertising":[2.1,1.9,2.7,3.0,3.6,3.2,2.7,2.4,1.8,1.6,1.3,1.9],
                   "month":range(12)
                  })
```

Now we're finally ready to create a candlestick chart, which is a very common tool used to analyze stock price data.  A candlestick chart shows the opening, closing, highest, and lowest price for a stock during a time window.  The color of the "candle" (the thick part of the bar) is green if the stock closed above its opening price, or red if below.

![Candlestick Example](img/candle.jpg)

This was initially designed to be a pandas plotting challenge, but it just so happens that this type of plot is just not feasible using pandas' methods.  If you are unfamiliar with matplotlib, we have provided a function that will plot the chart for you so long as you can use pandas to get the data into the correct format.

Your first step should be to get the data in the correct format using pandas' time-series grouping function.  We would like each candle to represent an hour's worth of data.  You can write your own aggregation function which returns the open/high/low/close, but pandas has a built-in which also does this.

The below cell contains helper functions.  Call ```day_stock_data()``` to generate a DataFrame containing the prices a hypothetical stock sold for, and the time the sale occurred.  Call ```plot_candlestick(df)``` on your properly aggregated and formatted stock data to print the candlestick chart.

In [ ]:
import numpy as np
def float_to_time(x):
    return str(int(x)) + ":" + str(int(x%1 * 60)).zfill(2) + ":" + str(int(x*60 % 1 * 60)).zfill(2)

def day_stock_data():
    #NYSE is open from 9:30 to 4:00
    time = 9.5
    price = 100
    results = [(float_to_time(time), price)]
    while time < 16:
        elapsed = np.random.exponential(.001)
        time += elapsed
        if time > 16:
            break
        price_diff = np.random.uniform(.999, 1.001)
        price *= price_diff
        results.append((float_to_time(time), price))
    
    
    df = pd.DataFrame(results, columns = ['time','price'])
    df.time = pd.to_datetime(df.time)
    return df

#Don't read me unless you get stuck!
def plot_candlestick(agg):
    """
    agg is a DataFrame which has a DatetimeIndex and five columns: ["open","high","low","close","color"]
    """
    fig, ax = plt.subplots()
    for time in agg.index:
        ax.plot([time.hour] * 2, agg.loc[time, ["high","low"]].values, color = "black")
        ax.plot([time.hour] * 2, agg.loc[time, ["open","close"]].values, color = agg.loc[time, "color"], linewidth = 10)

    ax.set_xlim((8,16))
    ax.set_ylabel("Price")
    ax.set_xlabel("Hour")
    ax.set_title("OHLC of Stock Value During Trading Day")
    plt.show()

**59.** Generate a day's worth of random stock data, and aggregate / reformat it so that it has hourly summaries of the opening, highest, lowest, and closing prices

**60.** Now that you have your properly-formatted data, try to plot it yourself as a candlestick chart.  Use the ```plot_candlestick(df)``` function above, or matplotlib's [```plot``` documentation](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.plot.html) if you get stuck.

*More exercises to follow soon...*