In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df_train = pd.read_csv("comment-category-prediction-challenge/train.csv") 
df_test = pd.read_csv("comment-category-prediction-challenge/test.csv") 

df_test["is_train"] = 0
df_train["is_train"] = 1
sample = pd.read_csv("comment-category-prediction-challenge/Sample.csv")

In [4]:
df_train.head()

,created_date,post_id,emoticon_1,emoticon_2,emoticon_3,upvote,downvote,if_1,if_2,race,religion,gender,disability,comment,label,is_train
0,2024-01-18 08:43:57.397508+00:00,73,0,0,0,0,1,0,10,NaN,NaN,NaN,False,She might be a bright spot for a party keou on...,2,1
1,2024-03-24 21:43:11.490017+00:00,39,0,0,0,6,0,0,4,NaN,NaN,NaN,False,"Under Alaska law, a non-tribal member is not b...",0,1
2,2024-04-24 20:32:17.014931+00:00,31,0,1,1,0,0,0,10,NaN,NaN,NaN,False,in the future please spare me your strawman dr...,2,1
3,2023-05-28 22:00:14.214527+00:00,39,0,0,0,5,0,0,10,NaN,NaN,NaN,False,"PS: That should have been ""rot"" instead of ""co...",2,1
4,2023-09-09 23:12:05.689498+00:00,39,0,0,0,0,0,0,10,NaN,NaN,NaN,False,"Today, the confederate flag...tomorrow, the na...",2,1

### Let's start with feature engi and EDA on both train and test data

In [5]:
df = pd.concat([df_train, df_test], ignore_index=True) #merged it so we can perform essentail eda and fe on both datasets
df

,created_date,post_id,emoticon_1,emoticon_2,emoticon_3,upvote,downvote,if_1,if_2,race,religion,gender,disability,comment,label,is_train
0,2024-01-18 08:43:57.397508+00:00,73,0,0,0,0,1,0,10,NaN,NaN,NaN,False,She might be a bright spot for a party keou on...,2.0,1
1,2024-03-24 21:43:11.490017+00:00,39,0,0,0,6,0,0,4,NaN,NaN,NaN,False,"Under Alaska law, a non-tribal member is not b...",0.0,1
2,2024-04-24 20:32:17.014931+00:00,31,0,1,1,0,0,0,10,NaN,NaN,NaN,False,in the future please spare me your strawman dr...,2.0,1
3,2023-05-28 22:00:14.214527+00:00,39,0,0,0,5,0,0,10,NaN,NaN,NaN,False,"PS: That should have been ""rot"" instead of ""co...",2.0,1
4,2023-09-09 23:12:05.689498+00:00,39,0,0,0,0,0,0,10,NaN,NaN,NaN,False,"Today, the confederate flag...tomorrow, the na...",2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,2023-09-26 03:14:06.328881+00:00,72,0,0,0,1,0,0,4,NaN,NaN,NaN,False,Working in McDonald's is easy (pain in the pos...,NaN,0
299996,2023-08-18 19:30:16.601996+00:00,71,2,0,0,1,0,10,4,none,christian,female,False,"In support of your first sentence, please prov...",NaN,0
299997,2023-10-26 15:41:55.972421+00:00,72,0,0,0,0,5,4,4,none,none,none,False,Cry us a river..\n\nhttp://www.celebritynetwor...,NaN,0
299998,2024-02-28 11:25:10.033561+00:00,72,1,0,0,0,0,0,4,NaN,NaN,NaN,False,tggv What does that have to do with Trudeau no...,NaN,0
299999,2022-12-30 06:10:30.575151+00:00,39,0,0,0,1,0,0,10,NaN,NaN,NaN,False,You bought at the top of the market my friend....,NaN,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   created_date  300000 non-null  str
 1   post_id       300000 non-null  int64
 2   emoticon_1    300000 non-null  int64
 3   emoticon_2    300000 non-null  int64
 4   emoticon_3    300000 non-null  int64
 5   upvote        300000 non-null  int64
 6   downvote      300000 non-null  int64
 7   if_1          300000 non-null  int64
 8   if_2          300000 non-null  int64
 9   race          79308 non-null   str
 10  religion      79308 non-null   str
 11  gender        79308 non-null   str
 12  disability    300000 non-null  bool
 13  comment       299999 non-null  str
 14  label         198000 non-null  float64
 15  is_train      300000 non-null  int64
dtypes: bool(1), float64(1), int64(9), str(5)
memory usage: 34.6 MB

In [7]:
display(df['race'].unique())
display(df['religion'].unique())
display(df['gender'].unique())
display(df['disability'].unique())
display(df['created_date'].unique())

<StringArray>
[nan, 'none', 'white', 'other', 'asian', 'black', 'latino']
Length: 7, dtype: str

<StringArray>
[        nan, 'christian',    'muslim',      'none',    'jewish',   'atheist',
     'other',     'hindu',  'buddhist']
Length: 9, dtype: str

<StringArray>
[nan, 'none', 'male', 'female', 'transgender', 'other']
Length: 6, dtype: str

array([False,  True])

<StringArray>
['2024-01-18 08:43:57.397508+00:00', '2024-03-24 21:43:11.490017+00:00',
 '2024-04-24 20:32:17.014931+00:00', '2023-05-28 22:00:14.214527+00:00',
 '2023-09-09 23:12:05.689498+00:00', '2024-04-06 20:10:59.141468+00:00',
 '2024-03-04 03:02:55.849172+00:00', '2023-10-14 20:57:30.208573+00:00',
 '2024-02-24 12:13:22.166045+00:00', '2023-08-07 20:35:35.968324+00:00',
 ...
 '2023-11-11 05:04:03.749590+00:00', '2024-04-06 08:41:04.924689+00:00',
 '2024-04-30 19:10:35.930782+00:00', '2024-05-04 07:53:11.994478+00:00',
 '2023-06-16 18:43:17.385957+00:00', '2023-09-26 03:14:06.328881+00:00',
 '2023-08-18 19:30:16.601996+00:00', '2023-10-26 15:41:55.972421+00:00',
 '2024-02-28 11:25:10.033561+00:00', '2022-12-30 06:10:30.575151+00:00']
Length: 299982, dtype: str

In [8]:
df[~df['race'].isna()]

,created_date,post_id,emoticon_1,emoticon_2,emoticon_3,upvote,downvote,if_1,if_2,race,religion,gender,disability,comment,label,is_train
8,2024-02-24 12:13:22.166045+00:00,71,0,0,0,0,0,6,6,none,christian,none,False,I wonder what our ancestors would say when the...,0.0,1
10,2023-12-26 01:06:22.590457+00:00,120,0,0,0,1,0,4,10,none,muslim,none,False,You're right the words Muslim ban came straigh...,1.0,1
12,2023-05-08 22:41:58.194759+00:00,31,0,0,0,2,0,4,10,none,none,none,False,Trump doesn't grasp even the little picture. H...,2.0,1
15,2024-03-13 02:27:09.785460+00:00,73,0,0,0,0,0,4,4,none,none,none,False,I believe its 1200 noon HST broadcast. rv,0.0,1
16,2023-07-12 03:19:48.796102+00:00,39,0,0,0,0,0,4,10,none,none,none,False,I did Google it.. Everything I read says it is...,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299966,2024-02-09 06:29:46.354475+00:00,72,0,0,0,3,1,4,4,none,none,none,False,"With all this talk of Trump , Paris agreement ...",NaN,0
299973,2023-11-06 20:20:14.259119+00:00,31,0,0,1,0,1,4,10,black,none,none,False,"If I were black and wanted to feel safe, I'd m...",NaN,0
299975,2023-04-11 19:39:24.171321+00:00,39,0,0,0,12,0,10,10,none,muslim,female,False,Clinton is wrong. Half of Trump's supporters a...,NaN,0
299996,2023-08-18 19:30:16.601996+00:00,71,2,0,0,1,0,10,4,none,christian,female,False,"In support of your first sentence, please prov...",NaN,0
299997,2023-10-26 15:41:55.972421+00:00,72,0,0,0,0,5,4,4,none,none,none,False,Cry us a river..\n\nhttp://www.celebritynetwor...,NaN,0

In [9]:
df['created_date'] = pd.to_datetime(df['created_date'], yearfirst=True)

In [10]:
# creating separate day, month, year
df['Day'] = pd.to_datetime(df['created_date'], yearfirst=True).dt.day.astype(int)
df['Month'] = pd.to_datetime(df['created_date'], yearfirst=True).dt.month.astype(int)
df['Year'] = pd.to_datetime(df['created_date'], yearfirst=True).dt.year.astype(int)
df

,created_date,post_id,emoticon_1,emoticon_2,emoticon_3,upvote,downvote,if_1,if_2,race,religion,gender,disability,comment,label,is_train,Day,Month,Year
0,2024-01-18 08:43:57.397508+00:00,73,0,0,0,0,1,0,10,NaN,NaN,NaN,False,She might be a bright spot for a party keou on...,2.0,1,18,1,2024
1,2024-03-24 21:43:11.490017+00:00,39,0,0,0,6,0,0,4,NaN,NaN,NaN,False,"Under Alaska law, a non-tribal member is not b...",0.0,1,24,3,2024
2,2024-04-24 20:32:17.014931+00:00,31,0,1,1,0,0,0,10,NaN,NaN,NaN,False,in the future please spare me your strawman dr...,2.0,1,24,4,2024
3,2023-05-28 22:00:14.214527+00:00,39,0,0,0,5,0,0,10,NaN,NaN,NaN,False,"PS: That should have been ""rot"" instead of ""co...",2.0,1,28,5,2023
4,2023-09-09 23:12:05.689498+00:00,39,0,0,0,0,0,0,10,NaN,NaN,NaN,False,"Today, the confederate flag...tomorrow, the na...",2.0,1,9,9,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,2023-09-26 03:14:06.328881+00:00,72,0,0,0,1,0,0,4,NaN,NaN,NaN,False,Working in McDonald's is easy (pain in the pos...,NaN,0,26,9,2023
299996,2023-08-18 19:30:16.601996+00:00,71,2,0,0,1,0,10,4,none,christian,female,False,"In support of your first sentence, please prov...",NaN,0,18,8,2023
299997,2023-10-26 15:41:55.972421+00:00,72,0,0,0,0,5,4,4,none,none,none,False,Cry us a river..\n\nhttp://www.celebritynetwor...,NaN,0,26,10,2023
299998,2024-02-28 11:25:10.033561+00:00,72,1,0,0,0,0,0,4,NaN,NaN,NaN,False,tggv What does that have to do with Trudeau no...,NaN,0,28,2,2024
299999,2022-12-30 06:10:30.575151+00:00,39,0,0,0,1,0,0,10,NaN,NaN,NaN,False,You bought at the top of the market my friend....,NaN,0,30,12,2022

In [11]:
df['weekday'] = pd.to_datetime(df['created_date'], yearfirst=True).dt.weekday.astype(int)

In [12]:
df['weekend'] = df['weekday'].isin([5,6]).astype(int) #to fetch the weekends
df['created_hour'] = pd.to_datetime(df['created_date']).dt.hour

In [13]:
df.post_id.unique()

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 22 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   created_date  300000 non-null  datetime64[us, UTC]
 1   post_id       300000 non-null  int64
 2   emoticon_1    300000 non-null  int64
 3   emoticon_2    300000 non-null  int64
 4   emoticon_3    300000 non-null  int64
 5   upvote        300000 non-null  int64
 6   downvote      300000 non-null  int64
 7   if_1          300000 non-null  int64
 8   if_2          300000 non-null  int64
 9   race          79308 non-null   str
 10  religion      79308 non-null   str
 11  gender        79308 non-null   str
 12  disability    300000 non-null  bool
 13  comment       299999 non-null  str
 14  label         198000 non-null  float64
 15  is_train      300000 non-null  int64
 16  Day           300000 non-null  int64
 17  Month         300000 non-null  int64
 18  Year          300000 non-null  int64
 19  weekday       300000 non-null  int64
 20  weekend       300000 non-null  int64
 21  created_hour  300000 non-null  int32
dtypes: bool(1), datetime64[us, UTC](1), float64(1), int32(1), int64(14), str(4)
memory usage: 47.2 MB

In [14]:
pd.get_dummies(df['race'])

        asian  black  latino   none  other  white
0       False  False   False  False  False  False
1       False  False   False  False  False  False
2       False  False   False  False  False  False
3       False  False   False  False  False  False
4       False  False   False  False  False  False
...       ...    ...     ...    ...    ...    ...
299995  False  False   False  False  False  False
299996  False  False   False   True  False  False
299997  False  False   False   True  False  False
299998  False  False   False  False  False  False
299999  False  False   False  False  False  False

[300000 rows x 6 columns]

### Handling categorical features: 
race, religion, gender : categorical to numerical

In [15]:
df.isna().sum()
# race, religion, gender : categorical to numerical
cols = ['race', 'religion', 'gender']
for i in cols:
    df[i+'_missing'] = df[i].isna().astype(int)
    df[i]= df[i].fillna("Missing").astype(str)

### Handling comments:

In [16]:
# handing missing vals:
df[df['comment'].isna()]
df['comment'] = df['comment'].fillna('').astype(str)

In [17]:
df['comment_len'] = df['comment'].str.len()
# df['comment'] = df['comment'].str.lower()
df['word_cnt'] = df['comment'].str.split().str.len()
# pd.set_option('display.max_colwidth', None)
# df['comment'].head()

In [18]:
# df['comment']= df['comment'].str.join(" ")
# cleaning and removing noise: 
df['comment'] = df['comment'].str.replace(r'http\S+', '', regex=True)
df['comment'] = df['comment'].str.replace(r'\s+', ' ', regex=True)
df[:3]['comment']

0    She might be a bright spot for a party keou on...
1    Under Alaska law, a non-tribal member is not b...
2    in the future please spare me your strawman dr...
Name: comment, dtype: str

In [19]:
df_train['comment']

0         She might be a bright spot for a party keou on...
1         Under Alaska law, a non-tribal member is not b...
2         in the future please spare me your strawman dr...
3         PS: That should have been "rot" instead of "co...
4         Today, the confederate flag...tomorrow, the na...
                                ...
197995    Why save people who are bent on self-destructi...
197996    Trudeau is not only undemocratic but also innu...
197997    block all exports no humanitarian relief and a...
197998    really black kids seeing that is better than g...
197999    Sounds likely since: "But now scientists have ...
Name: comment, Length: 198000, dtype: str

In [20]:
#some text intensive features:
df['num_!'] = df['comment'].str.count('!')
df['num_ques'] = df['comment'].str.count(r'\?')

In [21]:
pd.set_option('display.max_colwidth', None)
df['comment'].head(3)

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             She might be a bright spot for a party keou on Oahu dominated by greedy criminals or ethically challenged individuals.
1                                                                                                                Under Alaska law, a non-tribal member is not bound to tribal court.. Living in a particular community does not change your rights under state and federal law. In this case, Connor can basically flip the bird to the tribal court and there's nothing they can actually do. The only courts it appears he is subject to are those formally established under state and federal law, which does not recognize this. The tribal court can at-best basically use it's influence to get tribal members and others in the community to refuse to associate with Connor and not do business with him, essentially acting like a shunning until Connor decides to leave.
2    in the future please spare me your strawman drivel, and if you can't manage an intelligent discussion, stick to posting on a public bathroom wall. That is not remotely what I believe. That's the mindless drivel your thoughts produced. Nor did I get the idea every prediction must come true for it to be true, again, that is the mindless drivel your thoughts produced. What I did state is every computer model as been proven wrong, time, and time again, and every fear mongering prediction herding sheep has failed to come to fruition. What you fail to understand in speaking in ignorance is the fact since I was 8 years old I have advocated ouf for stronger EPA laws, which has nothing to do with this ridiculous nonsense of " manmade global warming."
Name: comment, dtype: str

### Handling Emojis and Imp columns

In [22]:
# df.info()
df['emoji_counts'] = df['emoticon_1']+df['emoticon_2']+df['emoticon_3']

In [23]:
s = "She might be a bright spot for a party keou on Oahu dominated by greedy criminals or ethically challenged individuals."
s.lower()

'she might be a bright spot for a party keou on oahu dominated by greedy criminals or ethically challenged individuals.'

### Handling Votes and performing FE on them: Engagement signls

**Let's see what all can we do with it:**
1. Total votes (we can simply sum them)
2. ratio of upvotes to downvotes(get the ratio)

*These are strong internal signal that'd be useful for prediction*

In [24]:
# df.info()
# df[['upvote', 'downvote']]
df['votes_ratio'] = df['upvote']/(df['upvote']+df['downvote']+ 1e-9) #learning: to avoid inf (0/0) add 1e-9 in denominator [it's basically adding a raelly tiny number 0.0000000001 to avoid 0/0 case]

In [25]:
#  balancing the magnitude : popularity magnitude or negative feedback magnitude using logx
df['upvote_log1'] = np.log1p(df['upvote'])
df['downvote_log1'] = np.log1p(df['downvote'])

In [26]:
#engagement scorea nd intensiryt
df['engagement_score'] = df['upvote'] - df['downvote']
df['emoticon_density'] = df['emoji_counts'] / (df['word_cnt'] + 1)

In [27]:
df.columns

Index(['created_date', 'post_id', 'emoticon_1', 'emoticon_2', 'emoticon_3',
       'upvote', 'downvote', 'if_1', 'if_2', 'race', 'religion', 'gender',
       'disability', 'comment', 'label', 'is_train', 'Day', 'Month', 'Year',
       'weekday', 'weekend', 'created_hour', 'race_missing',
       'religion_missing', 'gender_missing', 'comment_len', 'word_cnt',
       'num_!', 'num_ques', 'emoji_counts', 'votes_ratio', 'upvote_log1',
       'downvote_log1', 'engagement_score', 'emoticon_density'],
      dtype='str')

In [28]:
# df['post_id'].unique()
# df.groupby('post_id').size().
post_counts = df[df['is_train']==1].groupby('post_id').size().rename('post_comments_count')
# rest not seen will just point to 0
df['post_comments_count'] = df['post_id'].map(post_counts).fillna(0).astype(int)

In [29]:
df[:5]

,created_date,post_id,emoticon_1,emoticon_2,emoticon_3,upvote,downvote,if_1,if_2,race,...,word_cnt,num_!,num_ques,emoji_counts,votes_ratio,upvote_log1,downvote_log1,engagement_score,emoticon_density,post_comments_count
0,2024-01-18 08:43:57.397508+00:00,73,0,0,0,0,1,0,10,Missing,...,20,0,0,0,0.0,0.000000,0.693147,-1,0.000000,14882
1,2024-03-24 21:43:11.490017+00:00,39,0,0,0,6,0,0,4,Missing,...,110,0,0,0,1.0,1.945910,0.000000,6,0.000000,40946
2,2024-04-24 20:32:17.014931+00:00,31,0,1,1,0,0,0,10,Missing,...,133,0,0,2,0.0,0.000000,0.000000,0,0.014925,17023
3,2023-05-28 22:00:14.214527+00:00,39,0,0,0,5,0,0,10,Missing,...,15,0,0,0,1.0,1.791759,0.000000,5,0.000000,40946
4,2023-09-09 23:12:05.689498+00:00,39,0,0,0,0,0,0,10,Missing,...,40,0,0,0,0.0,0.000000,0.000000,0,0.000000,40946

In [30]:
# df.drop(['created_date'], axis = 1, inplace=True)
# df.dtypes
df.duplicated(subset=['created_date', 'post_id', 'emoticon_1', 'emoticon_2', 'emoticon_3',
       'upvote', 'downvote', 'if_1', 'if_2', 'race', 'religion', 'gender',
       'disability', 'label', 'is_train', 'Day', 'Month', 'Year',
       'weekday', 'race_missing', 'religion_missing', 'gender_missing',
       'comment_len', 'word_cnt', 'emoji_counts', 'votes_ratio', 'upvote_log1',
       'downvote_log1']).sum() # the comment col is list, to avoid typeerror

np.int64(0)

In [31]:
# missing flags 
display(df.describe().T)
display(df.info())

,count,mean,std,min,25%,50%,75%,max
post_id,300000.0,68.417507,27.939911,20.0,39.0,72.000000,72.000000,129.000000
emoticon_1,300000.0,0.279873,1.030117,0.0,0.0,0.000000,0.000000,95.000000
emoticon_2,300000.0,0.048343,0.258069,0.0,0.0,0.000000,0.000000,11.000000
emoticon_3,300000.0,0.120333,0.480833,0.0,0.0,0.000000,0.000000,19.000000
upvote,300000.0,2.608460,5.024763,0.0,0.0,1.000000,3.000000,201.000000
downvote,300000.0,0.664787,2.017886,0.0,0.0,0.000000,1.000000,107.000000
if_1,300000.0,1.905107,25.854302,0.0,0.0,0.000000,4.000000,1866.000000
if_2,300000.0,7.956210,14.958419,3.0,4.0,6.000000,10.000000,1833.000000
label,198000.0,0.793965,0.979808,0.0,0.0,0.000000,2.000000,3.000000
is_train,300000.0,0.660000,0.473710,0.0,0.0,1.000000,1.000000,1.000000
Day,300000.0,15.620303,8.841011,1.0,8.0,16.000000,23.000000,31.000000
Month,300000.0,5.953480,3.460371,1.0,3.0,5.000000,9.000000,12.000000
Year,300000.0,2023.416910,0.564651,2022.0,2023.0,2023.000000,2024.000000,2024.000000
weekday,300000.0,3.067820,2.060968,0.0,1.0,3.000000,5.000000,6.000000
weekend,300000.0,0.313417,0.463883,0.0,0.0,0.000000,1.000000,1.000000
created_hour,300000.0,12.137073,8.082762,0.0,4.0,13.000000,20.000000,23.000000
race_missing,300000.0,0.735640,0.440993,0.0,0.0,1.000000,1.000000,1.000000
religion_missing,300000.0,0.735640,0.440993,0.0,0.0,1.000000,1.000000,1.000000
gender_missing,300000.0,0.735640,0.440993,0.0,0.0,1.000000,1.000000,1.000000
comment_len,300000.0,302.852617,266.152127,0.0,102.0,211.000000,419.000000,1892.000000
word_cnt,300000.0,52.402213,45.734946,0.0,18.0,37.000000,73.000000,315.000000
num_!,300000.0,0.224583,0.976030,0.0,0.0,0.000000,0.000000,96.000000
num_ques,300000.0,0.435120,0.981733,0.0,0.0,0.000000,1.000000,49.000000
emoji_counts,300000.0,0.448550,1.259682,0.0,0.0,0.000000,0.000000,97.000000
votes_ratio,300000.0,0.521384,0.458046,0.0,0.0,0.666667,1.000000,1.000000
upvote_log1,300000.0,0.835440,0.861031,0.0,0.0,0.693147,1.386294,5.308268
downvote_log1,300000.0,0.280301,0.548439,0.0,0.0,0.000000,0.693147,4.682131
engagement_score,300000.0,1.943673,4.793989,-81.0,0.0,1.000000,3.000000,189.000000
emoticon_density,300000.0,0.022095,0.092522,0.0,0.0,0.000000,0.000000,7.333333
post_comments_count,300000.0,39703.576157,24464.281553,1.0,17023.0,40946.000000,69529.000000,69529.000000

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 36 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   created_date         300000 non-null  datetime64[us, UTC]
 1   post_id              300000 non-null  int64
 2   emoticon_1           300000 non-null  int64
 3   emoticon_2           300000 non-null  int64
 4   emoticon_3           300000 non-null  int64
 5   upvote               300000 non-null  int64
 6   downvote             300000 non-null  int64
 7   if_1                 300000 non-null  int64
 8   if_2                 300000 non-null  int64
 9   race                 300000 non-null  str
 10  religion             300000 non-null  str
 11  gender               300000 non-null  str
 12  disability           300000 non-null  bool
 13  comment              300000 non-null  str
 14  label                198000 non-null  float64
 15  is_train             300000 non-null  int64
 16  Day                  300000 non-null  int64
 17  Month                300000 non-null  int64
 18  Year                 300000 non-null  int64
 19  weekday              300000 non-null  int64
 20  weekend              300000 non-null  int64
 21  created_hour         300000 non-null  int32
 22  race_missing         300000 non-null  int64
 23  religion_missing     300000 non-null  int64
 24  gender_missing       300000 non-null  int64
 25  comment_len          300000 non-null  int64
 26  word_cnt             300000 non-null  int64
 27  num_!                300000 non-null  int64
 28  num_ques             300000 non-null  int64
 29  emoji_counts         300000 non-null  int64
 30  votes_ratio          300000 non-null  float64
 31  upvote_log1          300000 non-null  float64
 32  downvote_log1        300000 non-null  float64
 33  engagement_score     300000 non-null  int64
 34  emoticon_density     300000 non-null  float64
 35  post_comments_count  300000 non-null  int64
dtypes: bool(1), datetime64[us, UTC](1), float64(5), int32(1), int64(24), str(4)
memory usage: 79.3 MB

None

In [32]:
# outliers 
def iqr(s):
    q1, q3 = s.quantile(0.25), s.quantile(0.75)
    iqr  = q3 - q1
    lower, upper = q1-1.5*iqr, q3+1.5*iqr 
    return lower, upper, (s<lower).sum(), (s>upper).sum()

print("the Extreme valeus are :")
for i in ['upvote', 'downvote', 'if_1', 'if_2']:
    l,u,below,above = iqr(df[i])
    print(f"{i}: lower={l:.2f}, upper={u:.2f}, below={below}, above={above}")

# df['upvote'].quantile(0.75)

the Extreme valeus are :
upvote: lower=-4.50, upper=7.50, below=0, above=26337
downvote: lower=-1.50, upper=2.50, below=0, above=22989
if_1: lower=-6.00, upper=10.00, below=0, above=127
if_2: lower=-5.00, upper=19.00, below=0, above=5938

### Splitting before Encoding and all

In [33]:
df['disability'] = df['disability'].astype(int) #0 is False and 1 is True

In [34]:
display(df['race'].unique(),
df['religion'].unique(),
df['gender'].unique(),
df['post_id'].unique())

<StringArray>
['Missing', 'none', 'white', 'other', 'asian', 'black', 'latino']
Length: 7, dtype: str

<StringArray>
[  'Missing', 'christian',    'muslim',      'none',    'jewish',   'atheist',
     'other',     'hindu',  'buddhist']
Length: 9, dtype: str

<StringArray>
['Missing', 'none', 'male', 'female', 'transgender', 'other']
Length: 6, dtype: str

array([ 73,  39,  31,  72,  71, 120,  40, 111,  64, 123,  61, 105,  84,
       118,  76,  24,  91,  85, 102,  70,  74,  77,  66,  93, 100,  87,
        83, 103, 101, 108, 115,  79,  89,  75, 104,  90,  95,  96,  67,
       129,  82,  50,  43,  42, 109,  88, 125,  86,  20, 113,  65, 110])

In [35]:
final_df = df.copy(deep=True)

In [36]:
# removing redundent cols:
final_df.drop(['created_date', 'Day', 'Month', 'Year'], axis=1, inplace=True)
final_df.drop(['upvote','downvote'], axis=1, inplace=True) #a few more

In [37]:
final_df.dtypes

post_id                  int64
emoticon_1               int64
emoticon_2               int64
emoticon_3               int64
if_1                     int64
if_2                     int64
race                       str
religion                   str
gender                     str
disability               int64
comment                    str
label                  float64
is_train                 int64
weekday                  int64
weekend                  int64
created_hour             int32
race_missing             int64
religion_missing         int64
gender_missing           int64
comment_len              int64
word_cnt                 int64
num_!                    int64
num_ques                 int64
emoji_counts             int64
votes_ratio            float64
upvote_log1            float64
downvote_log1          float64
engagement_score         int64
emoticon_density       float64
post_comments_count      int64
dtype: object

In [38]:
#Splitting the train and test
train_df = final_df[final_df['is_train'] == 1].copy(deep= True)
test_df = final_df[final_df['is_train'] == 0].copy(deep= True)

In [39]:
print(train_df.shape
, final_df.shape, df_train.shape) #just to verfiy the splitting wnet smoothly

print(test_df.shape
, final_df.shape, df_test.shape)

(198000, 30) (300000, 30) (198000, 16)
(102000, 30) (300000, 30) (102000, 15)

### After splitting train and test data: Real ML

In [56]:
train_df.columns

Index(['post_id', 'emoticon_1', 'emoticon_2', 'emoticon_3', 'if_1', 'if_2',
       'race', 'religion', 'gender', 'disability', 'comment', 'label',
       'is_train', 'weekday', 'weekend', 'created_hour', 'race_missing',
       'religion_missing', 'gender_missing', 'comment_len', 'word_cnt',
       'num_!', 'num_ques', 'emoji_counts', 'votes_ratio', 'upvote_log1',
       'downvote_log1', 'engagement_score', 'emoticon_density',
       'post_comments_count'],
      dtype='str')

In [88]:
x_ = train_df.drop(columns=['label','post_id'])
y_ = train_df['label'].astype(int).values
x_.shape, y_.shape

((198000, 28), (198000,))

In [90]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    x_,
    y_,
    test_size=0.2,
    stratify=y_,
    random_state=42
)

## Encoding categorical features:

In [91]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=True) #to avoid crash on unseen dataset

In [92]:
categories = ['race', 'religion', 'gender']

X_train_ohe = ohe.fit_transform(X_train[categories])
X_val_ohe = ohe.transform(X_val[categories])
X_test_ohe = ohe.transform(test_df[categories])

In [ ]:
# encoded_df = pd.DataFrame(X_train_ohe.toarray(), columns= ohe.get_feature_names_out(['race', 'religion', 'gender']))
# display(encoded_df.head()) # the encoded data

,race_Missing,race_asian,race_black,race_latino,race_none,race_other,race_white,religion_Missing,religion_atheist,religion_buddhist,...,religion_jewish,religion_muslim,religion_none,religion_other,gender_Missing,gender_female,gender_male,gender_none,gender_other,gender_transgender
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

### Using TF-IDF for comments

In [93]:
train_df.shape

(198000, 30)

In [94]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=20000, 
                        ngram_range=(1,2), 
                        min_df=5, 
                        stop_words='english', 
                        lowercase=True
)

In [95]:
X_train_text = tfidf.fit_transform(X_train['comment'])
X_val_text = tfidf.transform(X_val['comment'])
X_test_text = tfidf.transform(test_df['comment'])

In [96]:
print(X_train_text.shape)
#prev: (198000, 20000)

(158400, 20000)

In [97]:
# train_df.drop(['post_id'], axis=1, inplace=True) #will decide later
#mergin the ohe and main dataset
numerical_col = ['emoticon_1', 'emoticon_2', 'emoticon_3', 'if_1', 
                'if_2','disability', 
                'weekday', 'weekend', 'created_hour', 'race_missing',
                'religion_missing', 'gender_missing', 'comment_len', 'word_cnt',
                'num_!', 'num_ques', 'emoji_counts', 'votes_ratio', 'upvote_log1',
                'downvote_log1', 'engagement_score', 'emoticon_density',
                'post_comments_count'] #excluded: ['post_id', 'comments']

In [98]:
#scalling the numericals 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_num = scaler.fit_transform(X_train[numerical_col])
X_val_num   = scaler.transform(X_val[numerical_col])
X_test_num  = scaler.transform(test_df[numerical_col])

In [99]:
#Merging everything 
from scipy.sparse import hstack

X_train_final = hstack([X_train_text, X_train_ohe, X_train_num])
X_val_final   = hstack([X_val_text, X_val_ohe, X_val_num])
X_test_final  = hstack([X_test_text, X_test_ohe, X_test_num])

In [100]:
from scipy.sparse import save_npz  #use load_npz for the same
save_npz('X_train_final.npz', X_train_final)
save_npz('X_val_final.npz', X_val_final)
save_npz('X_test_final.npz', X_test_final)

In [104]:
# y_train.('y_train.csv', index  = False)
# y_val.to_csv('y_val.csv', index  = False)
np.save('y_train', y_train)
np.save('y_val', y_val)

### Merger for final Dataset

In [ ]:
# from scipy.sparse import csr_matrix

# X_train_num = csr_matrix(train_df[numerical_col].values)
# X_test_num = csr_matrix(test_df[numerical_col].values)

In [ ]:
# #merge all
# from scipy.sparse import hstack

# X_train = hstack([X_train_num, X_train_ohe, X_train_text], format='csr')
# X_test = hstack([X_test_num, X_test_ohe, X_test_text], format='csr')

In [ ]:
# Am saving the manipulated dataset here so we can perform modelling in another notebook
# from scipy.sparse import save_npz  #use load_npz for the same
# save_npz('X_train_.npz', X_train)
# save_npz('X_test_.npz', X_test)

In [ ]:
# print(X_train.shape)
# print(X_test.shape)

(198000, 20045)
(102000, 20045)

In [ ]:
# train_df['label']

0         2.0
1         0.0
2         2.0
3         2.0
4         2.0
         ...
197995    0.0
197996    2.0
197997    3.0
197998    1.0
197999    0.0
Name: label, Length: 198000, dtype: float64

## visualisations and insigsts

In [53]:
# will go the visaulising in another notebook
# final_df.to_csv('final_df.csv', index  = False)
# train_df.to_csv('train_df.csv', index  = False)

In [54]:
df.to_csv('df.csv', index  = False)

### **Updation after analysising with visualisations:**

Alright after seeing the accuracy results

### **Model training and testing**

In [ ]:
from sentence_transformers import SentenceTransformer

In [55]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=2000,
    class_weight='balanced',
    n_jobs=-1
)